/*
 * generated by Xtext 2.22.0
 */
package org.bumble.eastadl.simplified.parser.antlr;

import org.antlr.runtime.Token;
import org.antlr.runtime.TokenSource;
import org.bumble.eastadl.simplified.parser.antlr.internal.InternalEastAdlSimplifiedParser;
import org.eclipse.xtext.parser.antlr.AbstractIndentationTokenSource;

public class EastAdlSimplifiedTokenSource extends AbstractIndentationTokenSource {

	public EastAdlSimplifiedTokenSource(TokenSource delegate) {
		super(delegate);
	}

	@Override
	protected boolean shouldSplitTokenImpl(Token token) {
		// TODO Review assumption
		return token.getType() == InternalEastAdlSimplifiedParser.RULE_WS;
	}

	@Override
	protected int getBeginTokenType() {
		// TODO Review assumption
		return InternalEastAdlSimplifiedParser.RULE_BEGIN;
	}

	@Override
	protected int getEndTokenType() {
		// TODO Review assumption
		return InternalEastAdlSimplifiedParser.RULE_END;
	}

}
