/*
 * generated by Xtext 2.22.0
 */
package org.bumble.eastadl.simplified.ide;


/**
 * Use this class to register ide components.
 */
public class EastAdlSimplifiedIdeModule extends AbstractEastAdlSimplifiedIdeModule {
}
