/*
 * generated by Xtext 2.22.0
 */
package org.bumble.eastadl.simplified.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.bumble.eastadl.simplified.EastAdlSimplifiedRuntimeModule;
import org.bumble.eastadl.simplified.EastAdlSimplifiedStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class EastAdlSimplifiedIdeSetup extends EastAdlSimplifiedStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new EastAdlSimplifiedRuntimeModule(), new EastAdlSimplifiedIdeModule()));
	}
	
}
