/**
 * generated by Xtext 2.25.0
 */
package org.bumble.eastadl.simplified.ui.wizard;

import org.eclipse.xtext.ui.wizard.template.AbstractFileTemplate;
import org.eclipse.xtext.ui.wizard.template.IFileTemplateProvider;

/**
 * Create a list with all file templates to be shown in the template new file wizard.
 * 
 * Each template is able to generate one or more files.
 */
@SuppressWarnings("all")
public class EastAdlSimplifiedFileTemplateProvider implements IFileTemplateProvider {
  @Override
  public AbstractFileTemplate[] getFileTemplates() {
    EmptyEatxtFile _emptyEatxtFile = new EmptyEatxtFile();
    return new AbstractFileTemplate[] { _emptyEatxtFile };
  }
}
