/**
 * generated by Xtext 2.25.0
 */
package org.bumble.eastadl.simplified.ui.wizard;

import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.ui.wizard.template.AbstractFileTemplate;
import org.eclipse.xtext.ui.wizard.template.FileTemplate;
import org.eclipse.xtext.ui.wizard.template.IFileGenerator;
import org.eclipse.xtext.ui.wizard.template.StringTemplateVariable;

@FileTemplate(label = "Empty EAtxt File", icon = "file_template.png", description = "Create an empty EAtxt file.")
@SuppressWarnings("all")
public final class EmptyEatxtFile extends AbstractFileTemplate {
  private final StringTemplateVariable packageName = this.text("Package Name", "Default");
  
  @Override
  public void generateFiles(final IFileGenerator generator) {
    StringConcatenation _builder = new StringConcatenation();
    String _folder = this.getFolder();
    _builder.append(_folder);
    _builder.append("/");
    String _name = this.getName();
    _builder.append(_name);
    _builder.append(".eatxt");
    StringConcatenation _builder_1 = new StringConcatenation();
    _builder_1.append("/*");
    _builder_1.newLine();
    _builder_1.append(" ");
    _builder_1.append("* This is an example model");
    _builder_1.newLine();
    _builder_1.append(" ");
    _builder_1.append("*/");
    _builder_1.newLine();
    _builder_1.append("EAPackage ");
    _builder_1.append(this.packageName);
    _builder_1.newLineIfNotEmpty();
    _builder_1.append("    ");
    _builder_1.newLine();
    generator.generate(_builder, _builder_1);
  }
}
