/*
 * generated by Xtext 2.22.0
 */
package org.bumble.eastadl.simplified.tests

import com.google.inject.Inject
import eastadl22_alpha.EAXML
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.extensions.InjectionExtension
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.jupiter.api.Assertions
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.^extension.ExtendWith

@ExtendWith(InjectionExtension)
@InjectWith(EastAdlSimplifiedInjectorProvider)
class EastAdlSimplifiedParsingTest {
	@Inject
	ParseHelper<EAXML> parseHelper
	
	@Test
	def void loadModel() {
		val result = parseHelper.parse('''
			Hello Xtext!
		''')
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')
	}
}
