/*
 * generated by Xtext 2.25.0
 */
package org.bumble.eastadl.simplified.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class EastAdlSimplifiedAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/bumble/eastadl/simplified/parser/antlr/internal/InternalEastAdlSimplifiedParser.tokens");
	}
}
