/*
 * generated by Xtext 2.22.0
 */
package org.bumble.eastadl.simplified.parser.antlr;

import com.google.inject.Inject;
import org.bumble.eastadl.simplified.parser.antlr.internal.InternalEastAdlSimplifiedParser;
import org.bumble.eastadl.simplified.services.EastAdlSimplifiedGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class EastAdlSimplifiedParser extends AbstractAntlrParser {

	@Inject
	private EastAdlSimplifiedGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalEastAdlSimplifiedParser createParser(XtextTokenStream stream) {
		return new InternalEastAdlSimplifiedParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Comment";
	}

	public EastAdlSimplifiedGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(EastAdlSimplifiedGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
