/*
 * generated by Xtext 2.22.0
 */
package org.bumble.eatxt.ui;

import org.bumble.eatxt.ui.AbstractEatxtUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class EatxtUiModule extends AbstractEatxtUiModule {

	public EatxtUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
