/*
 * generated by Xtext 2.25.0
 */
package org.bumble.eastadl.simplified.scoping;

import org.eclipse.xtext.xbase.scoping.batch.XbaseBatchScopeProvider;

public abstract class AbstractEastAdlSimplifiedScopeProvider extends XbaseBatchScopeProvider {
}
