/*
 * generated by Xtext 2.22.0
 */
package org.bumble.eatxt.validation;

import org.bumble.eatxt.validation.AbstractEatxtValidator;

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
public class EatxtValidator extends AbstractEatxtValidator {
	
//	public static final String INVALID_NAME = "invalidName";
//
//	@Check
//	public void checkGreetingStartsWithCapital(Greeting greeting) {
//		if (!Character.isUpperCase(greeting.getName().charAt(0))) {
//			warning("Name should start with a capital",
//					EastAdlSimplifiedPackage.Literals.GREETING__NAME,
//					INVALID_NAME);
//		}
//	}
	
}
