/*
 * generated by Xtext 2.22.0
 */
package org.bumble.eastadl.simplified.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class EastAdlSimplifiedUiModule extends AbstractEastAdlSimplifiedUiModule {

	public EastAdlSimplifiedUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
