/*
 * generated by Xtext 2.25.0
 */
package org.bumble.eastadl.simplified.serializer;

import com.google.inject.Inject;
import java.util.List;
import org.bumble.eastadl.simplified.services.EastAdlSimplifiedGrammarAccess;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.IGrammarAccess;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.nodemodel.INode;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AbstractElementAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.GroupAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.TokenAlias;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynNavigable;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynTransition;
import org.eclipse.xtext.serializer.sequencer.AbstractSyntacticSequencer;

@SuppressWarnings("all")
public class EastAdlSimplifiedSyntacticSequencer extends AbstractSyntacticSequencer {

	protected EastAdlSimplifiedGrammarAccess grammarAccess;
	protected AbstractElementAlias match_Actuator___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_12__q;
	protected AbstractElementAlias match_Allocation___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_6__q;
	protected AbstractElementAlias match_AnalysisFunctionType_Impl___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_12__q;
	protected AbstractElementAlias match_BasicSoftwareFunctionType___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_12__q;
	protected AbstractElementAlias match_CommunicationHardwarePin___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_7__q;
	protected AbstractElementAlias match_DesignFunctionType_Impl___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_12__q;
	protected AbstractElementAlias match_DesignLevel___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_10__q;
	protected AbstractElementAlias match_EABoolean___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_7__q;
	protected AbstractElementAlias match_EANumerical___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_10__q;
	protected AbstractElementAlias match_EAPackage___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_7__q;
	protected AbstractElementAlias match_EAString___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_7__q;
	protected AbstractElementAlias match_ElectricalComponent___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_13__q;
	protected AbstractElementAlias match_EnumerationLiteral___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_5__q;
	protected AbstractElementAlias match_FunctionClientServerInterface___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_8__q;
	protected AbstractElementAlias match_FunctionalDevice___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_12__q;
	protected AbstractElementAlias match_HardwareComponentType_Impl___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_12__q;
	protected AbstractElementAlias match_HardwareFunctionType___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_13__q;
	protected AbstractElementAlias match_HardwarePort___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_9__q;
	protected AbstractElementAlias match_IOHardwarePin___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_8__q;
	protected AbstractElementAlias match_LocalDeviceManager___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_12__q;
	protected AbstractElementAlias match_Node___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_13__q;
	protected AbstractElementAlias match_Operation___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_7__q;
	protected AbstractElementAlias match_PortGroup___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_7__q;
	protected AbstractElementAlias match_PowerHardwarePin___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_7__q;
	protected AbstractElementAlias match_Sensor___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_12__q;
	
	@Inject
	protected void init(IGrammarAccess access) {
		grammarAccess = (EastAdlSimplifiedGrammarAccess) access;
		match_Actuator___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_12__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getActuatorAccess().getLeftCurlyBracketKeyword_2_0()), new TokenAlias(false, false, grammarAccess.getActuatorAccess().getRightCurlyBracketKeyword_2_12()));
		match_Allocation___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_6__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getAllocationAccess().getLeftCurlyBracketKeyword_2_0()), new TokenAlias(false, false, grammarAccess.getAllocationAccess().getRightCurlyBracketKeyword_2_6()));
		match_AnalysisFunctionType_Impl___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_12__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getAnalysisFunctionType_ImplAccess().getLeftCurlyBracketKeyword_2_0()), new TokenAlias(false, false, grammarAccess.getAnalysisFunctionType_ImplAccess().getRightCurlyBracketKeyword_2_12()));
		match_BasicSoftwareFunctionType___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_12__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getBasicSoftwareFunctionTypeAccess().getLeftCurlyBracketKeyword_2_0()), new TokenAlias(false, false, grammarAccess.getBasicSoftwareFunctionTypeAccess().getRightCurlyBracketKeyword_2_12()));
		match_CommunicationHardwarePin___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_7__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getCommunicationHardwarePinAccess().getLeftCurlyBracketKeyword_2_0()), new TokenAlias(false, false, grammarAccess.getCommunicationHardwarePinAccess().getRightCurlyBracketKeyword_2_7()));
		match_DesignFunctionType_Impl___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_12__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getDesignFunctionType_ImplAccess().getLeftCurlyBracketKeyword_2_0()), new TokenAlias(false, false, grammarAccess.getDesignFunctionType_ImplAccess().getRightCurlyBracketKeyword_2_12()));
		match_DesignLevel___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_10__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getDesignLevelAccess().getLeftCurlyBracketKeyword_2_0()), new TokenAlias(false, false, grammarAccess.getDesignLevelAccess().getRightCurlyBracketKeyword_2_10()));
		match_EABoolean___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_7__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getEABooleanAccess().getLeftCurlyBracketKeyword_2_0()), new TokenAlias(false, false, grammarAccess.getEABooleanAccess().getRightCurlyBracketKeyword_2_7()));
		match_EANumerical___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_10__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getEANumericalAccess().getLeftCurlyBracketKeyword_2_0()), new TokenAlias(false, false, grammarAccess.getEANumericalAccess().getRightCurlyBracketKeyword_2_10()));
		match_EAPackage___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_7__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getEAPackageAccess().getLeftCurlyBracketKeyword_2_0()), new TokenAlias(false, false, grammarAccess.getEAPackageAccess().getRightCurlyBracketKeyword_2_7()));
		match_EAString___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_7__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getEAStringAccess().getLeftCurlyBracketKeyword_2_0()), new TokenAlias(false, false, grammarAccess.getEAStringAccess().getRightCurlyBracketKeyword_2_7()));
		match_ElectricalComponent___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_13__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getElectricalComponentAccess().getLeftCurlyBracketKeyword_2_0()), new TokenAlias(false, false, grammarAccess.getElectricalComponentAccess().getRightCurlyBracketKeyword_2_13()));
		match_EnumerationLiteral___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_5__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getEnumerationLiteralAccess().getLeftCurlyBracketKeyword_2_0()), new TokenAlias(false, false, grammarAccess.getEnumerationLiteralAccess().getRightCurlyBracketKeyword_2_5()));
		match_FunctionClientServerInterface___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_8__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getFunctionClientServerInterfaceAccess().getLeftCurlyBracketKeyword_2_0()), new TokenAlias(false, false, grammarAccess.getFunctionClientServerInterfaceAccess().getRightCurlyBracketKeyword_2_8()));
		match_FunctionalDevice___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_12__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getFunctionalDeviceAccess().getLeftCurlyBracketKeyword_2_0()), new TokenAlias(false, false, grammarAccess.getFunctionalDeviceAccess().getRightCurlyBracketKeyword_2_12()));
		match_HardwareComponentType_Impl___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_12__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getHardwareComponentType_ImplAccess().getLeftCurlyBracketKeyword_2_0()), new TokenAlias(false, false, grammarAccess.getHardwareComponentType_ImplAccess().getRightCurlyBracketKeyword_2_12()));
		match_HardwareFunctionType___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_13__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getHardwareFunctionTypeAccess().getLeftCurlyBracketKeyword_2_0()), new TokenAlias(false, false, grammarAccess.getHardwareFunctionTypeAccess().getRightCurlyBracketKeyword_2_13()));
		match_HardwarePort___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_9__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getHardwarePortAccess().getLeftCurlyBracketKeyword_2_0()), new TokenAlias(false, false, grammarAccess.getHardwarePortAccess().getRightCurlyBracketKeyword_2_9()));
		match_IOHardwarePin___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_8__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getIOHardwarePinAccess().getLeftCurlyBracketKeyword_2_0()), new TokenAlias(false, false, grammarAccess.getIOHardwarePinAccess().getRightCurlyBracketKeyword_2_8()));
		match_LocalDeviceManager___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_12__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getLocalDeviceManagerAccess().getLeftCurlyBracketKeyword_2_0()), new TokenAlias(false, false, grammarAccess.getLocalDeviceManagerAccess().getRightCurlyBracketKeyword_2_12()));
		match_Node___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_13__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getNodeAccess().getLeftCurlyBracketKeyword_2_0()), new TokenAlias(false, false, grammarAccess.getNodeAccess().getRightCurlyBracketKeyword_2_13()));
		match_Operation___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_7__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getOperationAccess().getLeftCurlyBracketKeyword_2_0()), new TokenAlias(false, false, grammarAccess.getOperationAccess().getRightCurlyBracketKeyword_2_7()));
		match_PortGroup___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_7__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getPortGroupAccess().getLeftCurlyBracketKeyword_2_0()), new TokenAlias(false, false, grammarAccess.getPortGroupAccess().getRightCurlyBracketKeyword_2_7()));
		match_PowerHardwarePin___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_7__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getPowerHardwarePinAccess().getLeftCurlyBracketKeyword_2_0()), new TokenAlias(false, false, grammarAccess.getPowerHardwarePinAccess().getRightCurlyBracketKeyword_2_7()));
		match_Sensor___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_12__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getSensorAccess().getLeftCurlyBracketKeyword_2_0()), new TokenAlias(false, false, grammarAccess.getSensorAccess().getRightCurlyBracketKeyword_2_12()));
	}
	
	@Override
	protected String getUnassignedRuleCallToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		return "";
	}
	
	
	@Override
	protected void emitUnassignedTokens(EObject semanticObject, ISynTransition transition, INode fromNode, INode toNode) {
		if (transition.getAmbiguousSyntaxes().isEmpty()) return;
		List<INode> transitionNodes = collectNodes(fromNode, toNode);
		for (AbstractElementAlias syntax : transition.getAmbiguousSyntaxes()) {
			List<INode> syntaxNodes = getNodesFor(transitionNodes, syntax);
			if (match_Actuator___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_12__q.equals(syntax))
				emit_Actuator___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_12__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Allocation___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_6__q.equals(syntax))
				emit_Allocation___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_6__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_AnalysisFunctionType_Impl___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_12__q.equals(syntax))
				emit_AnalysisFunctionType_Impl___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_12__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_BasicSoftwareFunctionType___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_12__q.equals(syntax))
				emit_BasicSoftwareFunctionType___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_12__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_CommunicationHardwarePin___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_7__q.equals(syntax))
				emit_CommunicationHardwarePin___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_7__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_DesignFunctionType_Impl___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_12__q.equals(syntax))
				emit_DesignFunctionType_Impl___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_12__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_DesignLevel___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_10__q.equals(syntax))
				emit_DesignLevel___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_10__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_EABoolean___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_7__q.equals(syntax))
				emit_EABoolean___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_7__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_EANumerical___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_10__q.equals(syntax))
				emit_EANumerical___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_10__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_EAPackage___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_7__q.equals(syntax))
				emit_EAPackage___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_7__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_EAString___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_7__q.equals(syntax))
				emit_EAString___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_7__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_ElectricalComponent___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_13__q.equals(syntax))
				emit_ElectricalComponent___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_13__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_EnumerationLiteral___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_5__q.equals(syntax))
				emit_EnumerationLiteral___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_5__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_FunctionClientServerInterface___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_8__q.equals(syntax))
				emit_FunctionClientServerInterface___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_8__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_FunctionalDevice___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_12__q.equals(syntax))
				emit_FunctionalDevice___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_12__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_HardwareComponentType_Impl___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_12__q.equals(syntax))
				emit_HardwareComponentType_Impl___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_12__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_HardwareFunctionType___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_13__q.equals(syntax))
				emit_HardwareFunctionType___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_13__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_HardwarePort___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_9__q.equals(syntax))
				emit_HardwarePort___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_9__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_IOHardwarePin___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_8__q.equals(syntax))
				emit_IOHardwarePin___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_8__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_LocalDeviceManager___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_12__q.equals(syntax))
				emit_LocalDeviceManager___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_12__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Node___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_13__q.equals(syntax))
				emit_Node___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_13__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Operation___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_7__q.equals(syntax))
				emit_Operation___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_7__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_PortGroup___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_7__q.equals(syntax))
				emit_PortGroup___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_7__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_PowerHardwarePin___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_7__q.equals(syntax))
				emit_PowerHardwarePin___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_7__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Sensor___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_12__q.equals(syntax))
				emit_Sensor___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_12__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else acceptNodes(getLastNavigableState(), syntaxNodes);
		}
	}

	/**
	 * Ambiguous syntax:
	 *     ('{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     shortName=Identifier (ambiguity) (rule end)
	 */
	protected void emit_Actuator___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_12__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     shortName=Identifier (ambiguity) (rule end)
	 */
	protected void emit_Allocation___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_6__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     shortName=Identifier (ambiguity) (rule end)
	 */
	protected void emit_AnalysisFunctionType_Impl___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_12__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     shortName=Identifier (ambiguity) (rule end)
	 */
	protected void emit_BasicSoftwareFunctionType___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_12__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     shortName=Identifier (ambiguity) (rule end)
	 */
	protected void emit_CommunicationHardwarePin___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_7__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     shortName=Identifier (ambiguity) (rule end)
	 */
	protected void emit_DesignFunctionType_Impl___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_12__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     shortName=Identifier (ambiguity) (rule end)
	 */
	protected void emit_DesignLevel___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_10__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     shortName=Identifier (ambiguity) (rule end)
	 */
	protected void emit_EABoolean___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_7__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     shortName=Identifier (ambiguity) (rule end)
	 */
	protected void emit_EANumerical___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_10__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     shortName=Identifier (ambiguity) (rule end)
	 */
	protected void emit_EAPackage___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_7__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     shortName=Identifier (ambiguity) (rule end)
	 */
	protected void emit_EAString___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_7__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     shortName=Identifier (ambiguity) (rule end)
	 */
	protected void emit_ElectricalComponent___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_13__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     shortName=Identifier (ambiguity) (rule end)
	 */
	protected void emit_EnumerationLiteral___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_5__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     shortName=Identifier (ambiguity) (rule end)
	 */
	protected void emit_FunctionClientServerInterface___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_8__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     shortName=Identifier (ambiguity) (rule end)
	 */
	protected void emit_FunctionalDevice___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_12__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     shortName=Identifier (ambiguity) (rule end)
	 */
	protected void emit_HardwareComponentType_Impl___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_12__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     shortName=Identifier (ambiguity) (rule end)
	 */
	protected void emit_HardwareFunctionType___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_13__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     shortName=Identifier (ambiguity) (rule end)
	 */
	protected void emit_HardwarePort___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_9__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     shortName=Identifier (ambiguity) (rule end)
	 */
	protected void emit_IOHardwarePin___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_8__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     shortName=Identifier (ambiguity) (rule end)
	 */
	protected void emit_LocalDeviceManager___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_12__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     shortName=Identifier (ambiguity) (rule end)
	 */
	protected void emit_Node___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_13__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     shortName=Identifier (ambiguity) (rule end)
	 */
	protected void emit_Operation___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_7__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     shortName=Identifier (ambiguity) (rule end)
	 */
	protected void emit_PortGroup___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_7__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     shortName=Identifier (ambiguity) (rule end)
	 */
	protected void emit_PowerHardwarePin___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_7__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     shortName=Identifier (ambiguity) (rule end)
	 */
	protected void emit_Sensor___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_12__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
}
