/*
 * generated by Xtext 2.25.0
 */
package org.bumble.eatxt.ui.wizard;

import org.eclipse.osgi.util.NLS;

public class Messages extends NLS {
	private static final String BUNDLE_NAME = "org.bumble.eatxt.ui.wizard.messages"; //$NON-NLS-1$
	
	public static String EmptyEatxtFile_Label;
	public static String EmptyEatxtFile_Description;
	public static String HelloWorldFile_Label;
	public static String HelloWorldFile_Description;
	
	static {
	// initialize resource bundle
	NLS.initializeMessages(BUNDLE_NAME, Messages.class);
	}
	
	private Messages() {
	}
}
