/*
 * generated by Xtext 2.22.0
 */
package org.bumble.eastadl.simplified.ui.tests;

import com.google.inject.Injector;
import org.bumble.eastadl.simplified.ui.internal.SimplifiedActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class EastAdlSimplifiedUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return SimplifiedActivator.getInstance().getInjector("org.bumble.eastadl.simplified.EastAdlSimplified");
	}

}
