/**
 */
package org.eclipse.eatop.eastadl21.edit.providers;

import java.util.ArrayList;
import java.util.Collection;

import org.eclipse.eatop.eastadl21.util.Eastadl21AdapterFactory;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class Eastadl21ItemProviderAdapterFactory extends Eastadl21AdapterFactory implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Eastadl21ItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.eatop.eastadl21.DesignLevel} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DesignLevelItemProvider designLevelItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.eatop.eastadl21.DesignLevel}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDesignLevelAdapter() {
		if (designLevelItemProvider == null) {
			designLevelItemProvider = new DesignLevelItemProvider(this);
		}

		return designLevelItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.eatop.eastadl21.Allocation} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AllocationItemProvider allocationItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.eatop.eastadl21.Allocation}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAllocationAdapter() {
		if (allocationItemProvider == null) {
			allocationItemProvider = new AllocationItemProvider(this);
		}

		return allocationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.eatop.eastadl21.AnalysisFunctionPrototype} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AnalysisFunctionPrototypeItemProvider analysisFunctionPrototypeItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.eatop.eastadl21.AnalysisFunctionPrototype}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAnalysisFunctionPrototypeAdapter() {
		if (analysisFunctionPrototypeItemProvider == null) {
			analysisFunctionPrototypeItemProvider = new AnalysisFunctionPrototypeItemProvider(this);
		}

		return analysisFunctionPrototypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.eatop.eastadl21.AnalysisFunctionType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AnalysisFunctionTypeItemProvider analysisFunctionTypeItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.eatop.eastadl21.AnalysisFunctionType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAnalysisFunctionTypeAdapter() {
		if (analysisFunctionTypeItemProvider == null) {
			analysisFunctionTypeItemProvider = new AnalysisFunctionTypeItemProvider(this);
		}

		return analysisFunctionTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.eatop.eastadl21.BasicSoftwareFunctionType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected BasicSoftwareFunctionTypeItemProvider basicSoftwareFunctionTypeItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.eatop.eastadl21.BasicSoftwareFunctionType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createBasicSoftwareFunctionTypeAdapter() {
		if (basicSoftwareFunctionTypeItemProvider == null) {
			basicSoftwareFunctionTypeItemProvider = new BasicSoftwareFunctionTypeItemProvider(this);
		}

		return basicSoftwareFunctionTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.eatop.eastadl21.DesignFunctionPrototype} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DesignFunctionPrototypeItemProvider designFunctionPrototypeItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.eatop.eastadl21.DesignFunctionPrototype}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDesignFunctionPrototypeAdapter() {
		if (designFunctionPrototypeItemProvider == null) {
			designFunctionPrototypeItemProvider = new DesignFunctionPrototypeItemProvider(this);
		}

		return designFunctionPrototypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.eatop.eastadl21.DesignFunctionType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DesignFunctionTypeItemProvider designFunctionTypeItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.eatop.eastadl21.DesignFunctionType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDesignFunctionTypeAdapter() {
		if (designFunctionTypeItemProvider == null) {
			designFunctionTypeItemProvider = new DesignFunctionTypeItemProvider(this);
		}

		return designFunctionTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.eatop.eastadl21.FunctionalDevice} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FunctionalDeviceItemProvider functionalDeviceItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.eatop.eastadl21.FunctionalDevice}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createFunctionalDeviceAdapter() {
		if (functionalDeviceItemProvider == null) {
			functionalDeviceItemProvider = new FunctionalDeviceItemProvider(this);
		}

		return functionalDeviceItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.eatop.eastadl21.FunctionAllocation} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FunctionAllocationItemProvider functionAllocationItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.eatop.eastadl21.FunctionAllocation}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createFunctionAllocationAdapter() {
		if (functionAllocationItemProvider == null) {
			functionAllocationItemProvider = new FunctionAllocationItemProvider(this);
		}

		return functionAllocationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.eatop.eastadl21.FunctionClientServerInterface} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FunctionClientServerInterfaceItemProvider functionClientServerInterfaceItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.eatop.eastadl21.FunctionClientServerInterface}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createFunctionClientServerInterfaceAdapter() {
		if (functionClientServerInterfaceItemProvider == null) {
			functionClientServerInterfaceItemProvider = new FunctionClientServerInterfaceItemProvider(this);
		}

		return functionClientServerInterfaceItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.eatop.eastadl21.FunctionClientServerPort} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FunctionClientServerPortItemProvider functionClientServerPortItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.eatop.eastadl21.FunctionClientServerPort}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createFunctionClientServerPortAdapter() {
		if (functionClientServerPortItemProvider == null) {
			functionClientServerPortItemProvider = new FunctionClientServerPortItemProvider(this);
		}

		return functionClientServerPortItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.eatop.eastadl21.FunctionConnector} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FunctionConnectorItemProvider functionConnectorItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.eatop.eastadl21.FunctionConnector}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createFunctionConnectorAdapter() {
		if (functionConnectorItemProvider == null) {
			functionConnectorItemProvider = new FunctionConnectorItemProvider(this);
		}

		return functionConnectorItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.eatop.eastadl21.FunctionFlowPort} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FunctionFlowPortItemProvider functionFlowPortItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.eatop.eastadl21.FunctionFlowPort}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createFunctionFlowPortAdapter() {
		if (functionFlowPortItemProvider == null) {
			functionFlowPortItemProvider = new FunctionFlowPortItemProvider(this);
		}

		return functionFlowPortItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.eatop.eastadl21.FunctionPowerPort} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FunctionPowerPortItemProvider functionPowerPortItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.eatop.eastadl21.FunctionPowerPort}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createFunctionPowerPortAdapter() {
		if (functionPowerPortItemProvider == null) {
			functionPowerPortItemProvider = new FunctionPowerPortItemProvider(this);
		}

		return functionPowerPortItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.eatop.eastadl21.HardwareFunctionType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected HardwareFunctionTypeItemProvider hardwareFunctionTypeItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.eatop.eastadl21.HardwareFunctionType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createHardwareFunctionTypeAdapter() {
		if (hardwareFunctionTypeItemProvider == null) {
			hardwareFunctionTypeItemProvider = new HardwareFunctionTypeItemProvider(this);
		}

		return hardwareFunctionTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.eatop.eastadl21.LocalDeviceManager} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected LocalDeviceManagerItemProvider localDeviceManagerItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.eatop.eastadl21.LocalDeviceManager}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createLocalDeviceManagerAdapter() {
		if (localDeviceManagerItemProvider == null) {
			localDeviceManagerItemProvider = new LocalDeviceManagerItemProvider(this);
		}

		return localDeviceManagerItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.eatop.eastadl21.Operation} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected OperationItemProvider operationItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.eatop.eastadl21.Operation}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createOperationAdapter() {
		if (operationItemProvider == null) {
			operationItemProvider = new OperationItemProvider(this);
		}

		return operationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.eatop.eastadl21.PortGroup} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PortGroupItemProvider portGroupItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.eatop.eastadl21.PortGroup}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPortGroupAdapter() {
		if (portGroupItemProvider == null) {
			portGroupItemProvider = new PortGroupItemProvider(this);
		}

		return portGroupItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.eatop.eastadl21.FunctionAllocation_allocatedElement} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FunctionAllocation_allocatedElementItemProvider functionAllocation_allocatedElementItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.eatop.eastadl21.FunctionAllocation_allocatedElement}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createFunctionAllocation_allocatedElementAdapter() {
		if (functionAllocation_allocatedElementItemProvider == null) {
			functionAllocation_allocatedElementItemProvider = new FunctionAllocation_allocatedElementItemProvider(this);
		}

		return functionAllocation_allocatedElementItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.eatop.eastadl21.FunctionAllocation_target} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FunctionAllocation_targetItemProvider functionAllocation_targetItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.eatop.eastadl21.FunctionAllocation_target}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createFunctionAllocation_targetAdapter() {
		if (functionAllocation_targetItemProvider == null) {
			functionAllocation_targetItemProvider = new FunctionAllocation_targetItemProvider(this);
		}

		return functionAllocation_targetItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.eatop.eastadl21.FunctionConnector_port} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FunctionConnector_portItemProvider functionConnector_portItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.eatop.eastadl21.FunctionConnector_port}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createFunctionConnector_portAdapter() {
		if (functionConnector_portItemProvider == null) {
			functionConnector_portItemProvider = new FunctionConnector_portItemProvider(this);
		}

		return functionConnector_portItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.eatop.eastadl21.Actuator} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ActuatorItemProvider actuatorItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.eatop.eastadl21.Actuator}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createActuatorAdapter() {
		if (actuatorItemProvider == null) {
			actuatorItemProvider = new ActuatorItemProvider(this);
		}

		return actuatorItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.eatop.eastadl21.CommunicationHardwarePin} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CommunicationHardwarePinItemProvider communicationHardwarePinItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.eatop.eastadl21.CommunicationHardwarePin}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCommunicationHardwarePinAdapter() {
		if (communicationHardwarePinItemProvider == null) {
			communicationHardwarePinItemProvider = new CommunicationHardwarePinItemProvider(this);
		}

		return communicationHardwarePinItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.eatop.eastadl21.ElectricalComponent} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ElectricalComponentItemProvider electricalComponentItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.eatop.eastadl21.ElectricalComponent}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createElectricalComponentAdapter() {
		if (electricalComponentItemProvider == null) {
			electricalComponentItemProvider = new ElectricalComponentItemProvider(this);
		}

		return electricalComponentItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.eatop.eastadl21.HardwareComponentPrototype} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected HardwareComponentPrototypeItemProvider hardwareComponentPrototypeItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.eatop.eastadl21.HardwareComponentPrototype}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createHardwareComponentPrototypeAdapter() {
		if (hardwareComponentPrototypeItemProvider == null) {
			hardwareComponentPrototypeItemProvider = new HardwareComponentPrototypeItemProvider(this);
		}

		return hardwareComponentPrototypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.eatop.eastadl21.HardwareComponentType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected HardwareComponentTypeItemProvider hardwareComponentTypeItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.eatop.eastadl21.HardwareComponentType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createHardwareComponentTypeAdapter() {
		if (hardwareComponentTypeItemProvider == null) {
			hardwareComponentTypeItemProvider = new HardwareComponentTypeItemProvider(this);
		}

		return hardwareComponentTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.eatop.eastadl21.HardwareConnector} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected HardwareConnectorItemProvider hardwareConnectorItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.eatop.eastadl21.HardwareConnector}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createHardwareConnectorAdapter() {
		if (hardwareConnectorItemProvider == null) {
			hardwareConnectorItemProvider = new HardwareConnectorItemProvider(this);
		}

		return hardwareConnectorItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.eatop.eastadl21.HardwarePort} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected HardwarePortItemProvider hardwarePortItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.eatop.eastadl21.HardwarePort}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createHardwarePortAdapter() {
		if (hardwarePortItemProvider == null) {
			hardwarePortItemProvider = new HardwarePortItemProvider(this);
		}

		return hardwarePortItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.eatop.eastadl21.HardwarePortConnector} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected HardwarePortConnectorItemProvider hardwarePortConnectorItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.eatop.eastadl21.HardwarePortConnector}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createHardwarePortConnectorAdapter() {
		if (hardwarePortConnectorItemProvider == null) {
			hardwarePortConnectorItemProvider = new HardwarePortConnectorItemProvider(this);
		}

		return hardwarePortConnectorItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.eatop.eastadl21.IOHardwarePin} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IOHardwarePinItemProvider ioHardwarePinItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.eatop.eastadl21.IOHardwarePin}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createIOHardwarePinAdapter() {
		if (ioHardwarePinItemProvider == null) {
			ioHardwarePinItemProvider = new IOHardwarePinItemProvider(this);
		}

		return ioHardwarePinItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.eatop.eastadl21.LogicalPortConnector} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected LogicalPortConnectorItemProvider logicalPortConnectorItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.eatop.eastadl21.LogicalPortConnector}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createLogicalPortConnectorAdapter() {
		if (logicalPortConnectorItemProvider == null) {
			logicalPortConnectorItemProvider = new LogicalPortConnectorItemProvider(this);
		}

		return logicalPortConnectorItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.eatop.eastadl21.Node} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected NodeItemProvider nodeItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.eatop.eastadl21.Node}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createNodeAdapter() {
		if (nodeItemProvider == null) {
			nodeItemProvider = new NodeItemProvider(this);
		}

		return nodeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.eatop.eastadl21.PowerHardwarePin} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PowerHardwarePinItemProvider powerHardwarePinItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.eatop.eastadl21.PowerHardwarePin}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPowerHardwarePinAdapter() {
		if (powerHardwarePinItemProvider == null) {
			powerHardwarePinItemProvider = new PowerHardwarePinItemProvider(this);
		}

		return powerHardwarePinItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.eatop.eastadl21.Sensor} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SensorItemProvider sensorItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.eatop.eastadl21.Sensor}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSensorAdapter() {
		if (sensorItemProvider == null) {
			sensorItemProvider = new SensorItemProvider(this);
		}

		return sensorItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.eatop.eastadl21.HardwareConnector_port} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected HardwareConnector_portItemProvider hardwareConnector_portItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.eatop.eastadl21.HardwareConnector_port}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createHardwareConnector_portAdapter() {
		if (hardwareConnector_portItemProvider == null) {
			hardwareConnector_portItemProvider = new HardwareConnector_portItemProvider(this);
		}

		return hardwareConnector_portItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.eatop.eastadl21.HardwarePortConnector_port} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected HardwarePortConnector_portItemProvider hardwarePortConnector_portItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.eatop.eastadl21.HardwarePortConnector_port}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createHardwarePortConnector_portAdapter() {
		if (hardwarePortConnector_portItemProvider == null) {
			hardwarePortConnector_portItemProvider = new HardwarePortConnector_portItemProvider(this);
		}

		return hardwarePortConnector_portItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.eatop.eastadl21.Comment} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CommentItemProvider commentItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.eatop.eastadl21.Comment}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCommentAdapter() {
		if (commentItemProvider == null) {
			commentItemProvider = new CommentItemProvider(this);
		}

		return commentItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.eatop.eastadl21.EAPackage} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EAPackageItemProvider eaPackageItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.eatop.eastadl21.EAPackage}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEAPackageAdapter() {
		if (eaPackageItemProvider == null) {
			eaPackageItemProvider = new EAPackageItemProvider(this);
		}

		return eaPackageItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.eatop.eastadl21.EAXML} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EAXMLItemProvider eaxmlItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.eatop.eastadl21.EAXML}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEAXMLAdapter() {
		if (eaxmlItemProvider == null) {
			eaxmlItemProvider = new EAXMLItemProvider(this);
		}

		return eaxmlItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.eatop.eastadl21.Rationale} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RationaleItemProvider rationaleItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.eatop.eastadl21.Rationale}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRationaleAdapter() {
		if (rationaleItemProvider == null) {
			rationaleItemProvider = new RationaleItemProvider(this);
		}

		return rationaleItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.eatop.eastadl21.Realization} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RealizationItemProvider realizationItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.eatop.eastadl21.Realization}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRealizationAdapter() {
		if (realizationItemProvider == null) {
			realizationItemProvider = new RealizationItemProvider(this);
		}

		return realizationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.eatop.eastadl21.Realization_realized} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Realization_realizedItemProvider realization_realizedItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.eatop.eastadl21.Realization_realized}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRealization_realizedAdapter() {
		if (realization_realizedItemProvider == null) {
			realization_realizedItemProvider = new Realization_realizedItemProvider(this);
		}

		return realization_realizedItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.eatop.eastadl21.Realization_realizedBy} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Realization_realizedByItemProvider realization_realizedByItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.eatop.eastadl21.Realization_realizedBy}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRealization_realizedByAdapter() {
		if (realization_realizedByItemProvider == null) {
			realization_realizedByItemProvider = new Realization_realizedByItemProvider(this);
		}

		return realization_realizedByItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.eatop.eastadl21.ArrayDatatype} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ArrayDatatypeItemProvider arrayDatatypeItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.eatop.eastadl21.ArrayDatatype}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createArrayDatatypeAdapter() {
		if (arrayDatatypeItemProvider == null) {
			arrayDatatypeItemProvider = new ArrayDatatypeItemProvider(this);
		}

		return arrayDatatypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.eatop.eastadl21.CompositeDatatype} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CompositeDatatypeItemProvider compositeDatatypeItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.eatop.eastadl21.CompositeDatatype}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCompositeDatatypeAdapter() {
		if (compositeDatatypeItemProvider == null) {
			compositeDatatypeItemProvider = new CompositeDatatypeItemProvider(this);
		}

		return compositeDatatypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.eatop.eastadl21.EABoolean} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EABooleanItemProvider eaBooleanItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.eatop.eastadl21.EABoolean}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEABooleanAdapter() {
		if (eaBooleanItemProvider == null) {
			eaBooleanItemProvider = new EABooleanItemProvider(this);
		}

		return eaBooleanItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.eatop.eastadl21.EADatatypePrototype} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EADatatypePrototypeItemProvider eaDatatypePrototypeItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.eatop.eastadl21.EADatatypePrototype}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEADatatypePrototypeAdapter() {
		if (eaDatatypePrototypeItemProvider == null) {
			eaDatatypePrototypeItemProvider = new EADatatypePrototypeItemProvider(this);
		}

		return eaDatatypePrototypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.eatop.eastadl21.EANumerical} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EANumericalItemProvider eaNumericalItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.eatop.eastadl21.EANumerical}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEANumericalAdapter() {
		if (eaNumericalItemProvider == null) {
			eaNumericalItemProvider = new EANumericalItemProvider(this);
		}

		return eaNumericalItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.eatop.eastadl21.EAString} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EAStringItemProvider eaStringItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.eatop.eastadl21.EAString}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEAStringAdapter() {
		if (eaStringItemProvider == null) {
			eaStringItemProvider = new EAStringItemProvider(this);
		}

		return eaStringItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.eatop.eastadl21.Enumeration} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EnumerationItemProvider enumerationItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.eatop.eastadl21.Enumeration}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEnumerationAdapter() {
		if (enumerationItemProvider == null) {
			enumerationItemProvider = new EnumerationItemProvider(this);
		}

		return enumerationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.eatop.eastadl21.EnumerationLiteral} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EnumerationLiteralItemProvider enumerationLiteralItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.eatop.eastadl21.EnumerationLiteral}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEnumerationLiteralAdapter() {
		if (enumerationLiteralItemProvider == null) {
			enumerationLiteralItemProvider = new EnumerationLiteralItemProvider(this);
		}

		return enumerationLiteralItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.eatop.eastadl21.Quantity} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected QuantityItemProvider quantityItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.eatop.eastadl21.Quantity}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createQuantityAdapter() {
		if (quantityItemProvider == null) {
			quantityItemProvider = new QuantityItemProvider(this);
		}

		return quantityItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.eatop.eastadl21.RangeableValueType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RangeableValueTypeItemProvider rangeableValueTypeItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.eatop.eastadl21.RangeableValueType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRangeableValueTypeAdapter() {
		if (rangeableValueTypeItemProvider == null) {
			rangeableValueTypeItemProvider = new RangeableValueTypeItemProvider(this);
		}

		return rangeableValueTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.eatop.eastadl21.Unit} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected UnitItemProvider unitItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.eatop.eastadl21.Unit}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createUnitAdapter() {
		if (unitItemProvider == null) {
			unitItemProvider = new UnitItemProvider(this);
		}

		return unitItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.eatop.eastadl21.EAArrayValue} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EAArrayValueItemProvider eaArrayValueItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.eatop.eastadl21.EAArrayValue}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEAArrayValueAdapter() {
		if (eaArrayValueItemProvider == null) {
			eaArrayValueItemProvider = new EAArrayValueItemProvider(this);
		}

		return eaArrayValueItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.eatop.eastadl21.EABooleanValue} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EABooleanValueItemProvider eaBooleanValueItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.eatop.eastadl21.EABooleanValue}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEABooleanValueAdapter() {
		if (eaBooleanValueItemProvider == null) {
			eaBooleanValueItemProvider = new EABooleanValueItemProvider(this);
		}

		return eaBooleanValueItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.eatop.eastadl21.EACompositeValue} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EACompositeValueItemProvider eaCompositeValueItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.eatop.eastadl21.EACompositeValue}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEACompositeValueAdapter() {
		if (eaCompositeValueItemProvider == null) {
			eaCompositeValueItemProvider = new EACompositeValueItemProvider(this);
		}

		return eaCompositeValueItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.eatop.eastadl21.EAEnumerationValue} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EAEnumerationValueItemProvider eaEnumerationValueItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.eatop.eastadl21.EAEnumerationValue}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEAEnumerationValueAdapter() {
		if (eaEnumerationValueItemProvider == null) {
			eaEnumerationValueItemProvider = new EAEnumerationValueItemProvider(this);
		}

		return eaEnumerationValueItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.eatop.eastadl21.EAExpression} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EAExpressionItemProvider eaExpressionItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.eatop.eastadl21.EAExpression}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEAExpressionAdapter() {
		if (eaExpressionItemProvider == null) {
			eaExpressionItemProvider = new EAExpressionItemProvider(this);
		}

		return eaExpressionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.eatop.eastadl21.EANumericalValue} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EANumericalValueItemProvider eaNumericalValueItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.eatop.eastadl21.EANumericalValue}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEANumericalValueAdapter() {
		if (eaNumericalValueItemProvider == null) {
			eaNumericalValueItemProvider = new EANumericalValueItemProvider(this);
		}

		return eaNumericalValueItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.eatop.eastadl21.EAStringValue} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EAStringValueItemProvider eaStringValueItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.eatop.eastadl21.EAStringValue}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEAStringValueAdapter() {
		if (eaStringValueItemProvider == null) {
			eaStringValueItemProvider = new EAStringValueItemProvider(this);
		}

		return eaStringValueItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.eatop.eastadl21.UserAttributeDefinition} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected UserAttributeDefinitionItemProvider userAttributeDefinitionItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.eatop.eastadl21.UserAttributeDefinition}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createUserAttributeDefinitionAdapter() {
		if (userAttributeDefinitionItemProvider == null) {
			userAttributeDefinitionItemProvider = new UserAttributeDefinitionItemProvider(this);
		}

		return userAttributeDefinitionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.eatop.eastadl21.UserAttributedElement} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected UserAttributedElementItemProvider userAttributedElementItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.eatop.eastadl21.UserAttributedElement}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createUserAttributedElementAdapter() {
		if (userAttributedElementItemProvider == null) {
			userAttributedElementItemProvider = new UserAttributedElementItemProvider(this);
		}

		return userAttributedElementItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.eatop.eastadl21.UserElementType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected UserElementTypeItemProvider userElementTypeItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.eatop.eastadl21.UserElementType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createUserElementTypeAdapter() {
		if (userElementTypeItemProvider == null) {
			userElementTypeItemProvider = new UserElementTypeItemProvider(this);
		}

		return userElementTypeItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>)type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void dispose() {
		if (designLevelItemProvider != null) designLevelItemProvider.dispose();
		if (allocationItemProvider != null) allocationItemProvider.dispose();
		if (analysisFunctionPrototypeItemProvider != null) analysisFunctionPrototypeItemProvider.dispose();
		if (analysisFunctionTypeItemProvider != null) analysisFunctionTypeItemProvider.dispose();
		if (basicSoftwareFunctionTypeItemProvider != null) basicSoftwareFunctionTypeItemProvider.dispose();
		if (designFunctionPrototypeItemProvider != null) designFunctionPrototypeItemProvider.dispose();
		if (designFunctionTypeItemProvider != null) designFunctionTypeItemProvider.dispose();
		if (functionalDeviceItemProvider != null) functionalDeviceItemProvider.dispose();
		if (functionAllocationItemProvider != null) functionAllocationItemProvider.dispose();
		if (functionClientServerInterfaceItemProvider != null) functionClientServerInterfaceItemProvider.dispose();
		if (functionClientServerPortItemProvider != null) functionClientServerPortItemProvider.dispose();
		if (functionConnectorItemProvider != null) functionConnectorItemProvider.dispose();
		if (functionFlowPortItemProvider != null) functionFlowPortItemProvider.dispose();
		if (functionPowerPortItemProvider != null) functionPowerPortItemProvider.dispose();
		if (hardwareFunctionTypeItemProvider != null) hardwareFunctionTypeItemProvider.dispose();
		if (localDeviceManagerItemProvider != null) localDeviceManagerItemProvider.dispose();
		if (operationItemProvider != null) operationItemProvider.dispose();
		if (portGroupItemProvider != null) portGroupItemProvider.dispose();
		if (functionAllocation_allocatedElementItemProvider != null) functionAllocation_allocatedElementItemProvider.dispose();
		if (functionAllocation_targetItemProvider != null) functionAllocation_targetItemProvider.dispose();
		if (functionConnector_portItemProvider != null) functionConnector_portItemProvider.dispose();
		if (actuatorItemProvider != null) actuatorItemProvider.dispose();
		if (communicationHardwarePinItemProvider != null) communicationHardwarePinItemProvider.dispose();
		if (electricalComponentItemProvider != null) electricalComponentItemProvider.dispose();
		if (hardwareComponentPrototypeItemProvider != null) hardwareComponentPrototypeItemProvider.dispose();
		if (hardwareComponentTypeItemProvider != null) hardwareComponentTypeItemProvider.dispose();
		if (hardwareConnectorItemProvider != null) hardwareConnectorItemProvider.dispose();
		if (hardwarePortItemProvider != null) hardwarePortItemProvider.dispose();
		if (hardwarePortConnectorItemProvider != null) hardwarePortConnectorItemProvider.dispose();
		if (ioHardwarePinItemProvider != null) ioHardwarePinItemProvider.dispose();
		if (logicalPortConnectorItemProvider != null) logicalPortConnectorItemProvider.dispose();
		if (nodeItemProvider != null) nodeItemProvider.dispose();
		if (powerHardwarePinItemProvider != null) powerHardwarePinItemProvider.dispose();
		if (sensorItemProvider != null) sensorItemProvider.dispose();
		if (hardwareConnector_portItemProvider != null) hardwareConnector_portItemProvider.dispose();
		if (hardwarePortConnector_portItemProvider != null) hardwarePortConnector_portItemProvider.dispose();
		if (commentItemProvider != null) commentItemProvider.dispose();
		if (eaPackageItemProvider != null) eaPackageItemProvider.dispose();
		if (eaxmlItemProvider != null) eaxmlItemProvider.dispose();
		if (rationaleItemProvider != null) rationaleItemProvider.dispose();
		if (realizationItemProvider != null) realizationItemProvider.dispose();
		if (realization_realizedItemProvider != null) realization_realizedItemProvider.dispose();
		if (realization_realizedByItemProvider != null) realization_realizedByItemProvider.dispose();
		if (arrayDatatypeItemProvider != null) arrayDatatypeItemProvider.dispose();
		if (compositeDatatypeItemProvider != null) compositeDatatypeItemProvider.dispose();
		if (eaBooleanItemProvider != null) eaBooleanItemProvider.dispose();
		if (eaDatatypePrototypeItemProvider != null) eaDatatypePrototypeItemProvider.dispose();
		if (eaNumericalItemProvider != null) eaNumericalItemProvider.dispose();
		if (eaStringItemProvider != null) eaStringItemProvider.dispose();
		if (enumerationItemProvider != null) enumerationItemProvider.dispose();
		if (enumerationLiteralItemProvider != null) enumerationLiteralItemProvider.dispose();
		if (quantityItemProvider != null) quantityItemProvider.dispose();
		if (rangeableValueTypeItemProvider != null) rangeableValueTypeItemProvider.dispose();
		if (unitItemProvider != null) unitItemProvider.dispose();
		if (eaArrayValueItemProvider != null) eaArrayValueItemProvider.dispose();
		if (eaBooleanValueItemProvider != null) eaBooleanValueItemProvider.dispose();
		if (eaCompositeValueItemProvider != null) eaCompositeValueItemProvider.dispose();
		if (eaEnumerationValueItemProvider != null) eaEnumerationValueItemProvider.dispose();
		if (eaExpressionItemProvider != null) eaExpressionItemProvider.dispose();
		if (eaNumericalValueItemProvider != null) eaNumericalValueItemProvider.dispose();
		if (eaStringValueItemProvider != null) eaStringValueItemProvider.dispose();
		if (userAttributeDefinitionItemProvider != null) userAttributeDefinitionItemProvider.dispose();
		if (userAttributedElementItemProvider != null) userAttributedElementItemProvider.dispose();
		if (userElementTypeItemProvider != null) userElementTypeItemProvider.dispose();
	}

}
