/*
 * generated by Xtext 2.25.0
 */
package org.bumble.eastadl.simplified.ui.editor;

import org.eclipse.xtext.xbase.ui.editor.XbaseEditor;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass.
 */
public class EastAdlSimplifiedEditor extends XbaseEditor {
}
