/*
 * generated by Xtext 2.22.0
 */
package org.bumble.eastadl.simplified.ui;

import com.google.inject.Injector;
import org.bumble.eastadl.simplified.ui.internal.SimplifiedActivator;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class EastAdlSimplifiedExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(SimplifiedActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		SimplifiedActivator activator = SimplifiedActivator.getInstance();
		return activator != null ? activator.getInjector(SimplifiedActivator.ORG_BUMBLE_EASTADL_SIMPLIFIED_EASTADLSIMPLIFIED) : null;
	}

}
