/*
 * generated by Xtext 2.25.0
 */
package org.bumble.eastadl.simplified.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractEastAdlSimplifiedScopeProvider extends DelegatingScopeProvider {
}
